services:
  nginx:
    ports: !override
      - "${CAMPUS_PUBLIC_BIND_ADDRESS:-10.20.10.193}:${CAMPUS_PUBLIC_HTTP_PORT:-80}:${NGINX_PORT:-80}"
      - "127.0.0.1:${EXPOSE_NGINX_PORT:-18080}:${NGINX_PORT:-80}"
      - "127.0.0.1:${CAMPUS_ADMIN_PORT:-18081}:8081"
